cul/ldpd-findingaids-asi

- app/controllers/repositories_controller.rb
- app/models/repository.rb
- app/views/repositories/index.html.erb
- config/routes.rb
- use a RepositoryController index action for the home page
https://issues.cul.columbia.edu/browse/ACFA-143
> ACFA-143 only link to repositories with list_of_finding_aids configured on home page

- app/views/components/_component_structure_view_print.html.erb
- app/views/components/_component_structure_view_style_a.html.erb
- app/views/components/_component_structure_view_style_b.html.erb
@fcd1 I made changes to three files per the ticket. Please review and put on Test if OK.
> acfa-148: change labels of digital content links

- app/views/application/_banner.html.erb
- app/views/application/_breadcrumbs.html.erb
- app/views/finding_aids/_subject_headings.html.erb
- app/views/finding_aids/_summary.html.erb
I updated cgi-bin links to the canonical URLs per the ticket. Please merge & deploy to test when convenient.
> Acfa 156 update cgi bin links

- app/views/application/_topnavbar.html.erb
> fixed nav bar links

- .gitignore
- README.md
- config/templates/blacklight.template.yml
- docker-compose.yml
- solr/conf/_rest_managed.json
- solr/conf/admin-extra.html
- solr/conf/elevate.xml
- solr/conf/mapping-ISOLatin1Accent.txt
- solr/conf/protwords.txt
- solr/conf/schema.xml
- solr/conf/solrconfig.xml
- solr/conf/spellings.txt
- solr/conf/stopwords.txt
- solr/conf/stopwords_en.txt
- solr/conf/synonyms.txt
- solr/conf/xslt/example.xsl
- solr/conf/xslt/example_atom.xsl
- solr/conf/xslt/example_rss.xsl
- solr/conf/xslt/luke.xsl
these configurations should support starting solr via `docker-compose up`
the solr should start on port 8983, and have a core named "acfa"
> add arclight solr8 configs for development and testing (ACFA-405)

- app/views/finding_aids/_summary.html.erb
I could not figure out how to make this work without getting rid of the red text for the RBML finding aids. I also decreased the indent of the "At a Glance" block.
> Line up access restrictions in summary

- app/assets/stylesheets/application.scss
- app/components/acfa/search_bar_component.html.erb
- app/components/acfa/top_navbar_component.rb
- app/helpers/application_helper.rb
- app/javascript/application.js
- app/models/solr_document.rb
- app/overrides/blacklight/link_alternate_presenter_override.rb
- app/views/aeon_requests/_aeon_request.html.erb
- app/views/catalog/_document.atom.builder
- app/views/catalog/_document.rss.builder
- app/views/catalog/index.json.jbuilder
- app/views/repositories/index.html.erb
- config/locales/arclight.en.yml
- config/routes.rb
- config/templates/repositories.template.yml
- spec/components/acfa/search_bar_component_spec.rb
- spec/support/controller_level_helpers.rb
- spec/views/catalog/_document.atom.builder_spec.rb
- spec/views/catalog/_document.rss.builder_spec.rb
- spec/views/catalog/index.json.builder_spec.rb
- Remove "at Columbia University" from top header
- fix an Arclight bug that hides the current "q" parameter in the search bar
- minor restyle to prevent displaying dropdown for all collections/this collection search when you cannot choose "this collection"
> Acfa 775 top header

- Gemfile
- Gemfile.lock
- app/components/acfa/document/group_component.html.erb
- lib/ead/traject/ead2_component_config.rb
- lib/ead/traject/ead2_config.rb
- spec/ead/traject/ead2_config_spec.rb
Remove no longer necessary customizations or update customizations to incorporate Arclight 1.1 changes
> Upgrade Arclight to 1.1

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
Keep page parameter when defaulting to group by collection. Adds related test.
> Fixes ACFA-486

- config/templates/repositories.template.yml
- lib/acfa/search_state.rb
- spec/acfa/search_state_spec.rb
- spec/fixtures/config/aspace_repositories.yml
- spec/views/catalog/_document.atom.builder_spec.rb
- spec/views/catalog/_document.rss.builder_spec.rb
- spec/views/catalog/index.json.builder_spec.rb
> Remove links to external ASpace PUI

- app/components/acfa/arclight/document_component.html.erb
- app/components/acfa/arclight/document_component.rb
- app/controllers/catalog_controller.rb
@barmintor Is there a more minimal way I could have done this?
> remove bookmark checkbox

- config/downloads.yml
> add PDF download functionality

- app/controllers/catalog_controller.rb
- config/locales/arclight.en.yml
at collection and component levels
> display additional notes

- solr/conf/solrconfig.xml
> update relevancy ranking in solrconfig

- solr/conf/schema.xml
fixed upstream in arclight in [PR 1440](https://github.com/projectblacklight/arclight/pull/1440)
> fixes typo in solr config

- lib/ead/traject/ead2_component_config.rb
- lib/ead/traject/ead2_config.rb
- spec/fixtures/ead/test_digital_objects/from_did.xml
- spec/models/repository_spec.rb
> Only link to hrefs that looks like URLs

- lib/ead/traject/ead2_component_config.rb
- lib/ead/traject/ead2_config.rb
- lib/ead/traject/ead2_shared.rb
- spec/ead/traject/ead2_config_spec.rb
- spec/fixtures/ead/test_ead.xml
differentiate extents in one <physdesc>
> fixes ACFA-587

- app/controllers/catalog_controller.rb
- config/locales/arclight.en.yml
- lib/ead/traject/ead2_config.rb
- spec/ead/traject/ead2_config_spec.rb
> Add local call number to administrative information

- lib/ead/traject/ead2_component_config.rb
- lib/ead/traject/ead2_config.rb
- spec/fixtures/ead/test_ead.xml
> exclude aspace uris when indexing call #s

- app/controllers/catalog_controller.rb
> Move preferred citation to admin info

- lib/ead/traject/ead2_component_config.rb
- lib/ead/traject/ead2_config.rb
> Include daogrp in has_online_content

- app/javascript/src/mirador.js
Honor multiasset display settings
> fixes ACFA-624

- lib/ead/traject/ead2_config.rb
- spec/ead/traject/ead2_config_spec.rb
> Count digital objects that are exported as daogrp in "items available online" 

- lib/ead/traject/ead2_config.rb
- spec/ead/traject/ead2_config_spec.rb
- spec/fixtures/ead/test_language/test_lang_aspace3x.xml
- spec/fixtures/ead/test_language/test_lang_aspace4x.xml
- spec/fixtures/ead/test_language/test_lang_note.xml
* account for changes to EAD export in ArchivesSpace 4.0
* fixes ACFA-642
> modify language indexing

- README.md
Adds documentation describing how to set up FontAwesome Free.
> ACFA-648 FontAwesome Free fallback documentation
